"use client";

import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";

type PromptRatingDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  promptName: string;
  onRate: (rating: number) => void;
};

export function PromptRatingDialog({
  open,
  onOpenChange,
  promptName,
  onRate,
}: PromptRatingDialogProps) {
  const [rating, setRating] = useState<number | null>(null);
  const [hoveredRating, setHoveredRating] = useState<number | null>(null);

  const handleSubmit = () => {
    if (rating !== null) {
      onRate(rating);
      setRating(null);
      setHoveredRating(null);
      onOpenChange(false);
    }
  };

  const handleSkip = () => {
    setRating(null);
    setHoveredRating(null);
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Rate Your Prompt</DialogTitle>
          <DialogDescription>
            How would you rate the quality of the summary generated by "{promptName}"?
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-6 py-4">
          <div className="space-y-2">
            <Label className="text-sm font-medium">Rating (1-10)</Label>
            <div className="flex items-center gap-2 flex-wrap">
              {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((num) => {
                const isSelected = rating === num;
                const isHovered = hoveredRating === num;
                const shouldHighlight = isSelected || isHovered;

                return (
                  <button
                    key={num}
                    type="button"
                    onClick={() => setRating(num)}
                    onMouseEnter={() => setHoveredRating(num)}
                    onMouseLeave={() => setHoveredRating(null)}
                    className={`
                      w-10 h-10 rounded-lg border-2 transition-all
                      ${shouldHighlight
                        ? "bg-[rgb(var(--accent))] text-white border-[rgb(var(--accent))] scale-110"
                        : "bg-[rgb(var(--muted))] border-[rgb(var(--border))] hover:border-[rgb(var(--accent))]"
                      }
                      font-semibold text-sm
                    `}
                  >
                    {num}
                  </button>
                );
              })}
            </div>
            <div className="flex items-center justify-between text-xs text-[rgb(var(--muted-foreground))] mt-2">
              <span>Poor</span>
              <span>Excellent</span>
            </div>
          </div>

          {rating !== null && (
            <div className="rounded-lg border border-[rgb(var(--border))] bg-[rgb(var(--muted))]/30 p-3">
              <p className="text-sm">
                You selected: <span className="font-semibold">{rating}/10</span>
              </p>
            </div>
          )}

          <div className="flex gap-2 justify-end">
            <Button variant="outline" onClick={handleSkip}>
              Skip
            </Button>
            <Button onClick={handleSubmit} disabled={rating === null}>
              Submit Rating
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}




