export const CATEGORIES = [
    "Arts / Design",
    "Biography / Memoir",
    "Business",
    "Career / Success",
    "Communication",
    "Economics",
    "Education",
    "Entertainment",
    "Entrepreneurship",
    "Fiction",
    "Food",
    "Health",
    "History",
    "Law",
    "Lifestyle",
    "Management / Leadership",
    "Marketing",
    "Media",
    "Money / Finance",
    "Motivation",
    "Parenting",
    "Philosophy",
    "Politics",
    "Productivity",
    "Psychology",
    "Relationships",
    "Sales",
    "Science",
    "Self-Improvement",
    "Society / Culture",
    "Spirituality",
    "Sports",
    "Technology"
] as const;

export type Category = typeof CATEGORIES[number];
